'use client';

import { useMemo } from 'react';
import type { Shot } from '@/features/score/types';
import type { HoleMapData } from '@/actions/hole-map';
import type { HoleArea } from '@/lib/geo';
import {
  computeInitialPositions,
  computeGreenCenter,
  pickCenterline,
  type AutoTrajectorySlot,
} from '@/features/score/lib/auto-trajectory';

/**
 * Sprint 7 PR1 (S-7a): 自動軌跡 + 詳細記録を合成する hook
 *
 * 設計参照: `_bmad-output/planning-artifacts/sprint7-auto-trajectory.md`
 *   Section 5.1.1 (型分離: displayedShots vs persistableShots)
 *
 * **責務**:
 * - ShotRecorder の既存ショット (詳細記録) + 自動補完スロット を合成して
 *   MultiShotPositionEditor に渡せる displayedShots を構築
 * - 保存パイプライン (buildShotSyncPayload) には自動スロットを混ぜない (型で分離)
 *
 * **保証**:
 * - 詳細記録は常に尊重 (位置 / クラブ / lie / 結果すべて保持)
 * - 不足分のみ自動補完 (詳細 2 個 + Par 4 → 自動 2 個追加で計 4 表示)
 * - 詳細 > 打数の場合は警告フラグを返す (UI で「不整合バナー」を出す)
 * - 自動補完の位置は centerline (or ref_start/end fallback) を polyline 距離補間
 *
 * **使い分け**:
 * - 表示用 (MultiShotPositionEditor / overlay): displayedShots を使う
 * - 保存用 (buildShotSyncPayload): persistableShots を使う
 */

/** 表示用ショット (自動スロットを含む) */
export interface DisplayedShot extends Shot {
  /** 自動生成スロット (DB 未保存) なら true */
  isAutoGenerated: boolean;
}

/** 保存パイプライン用ショット (詳細記録のみ、自動スロット除外) */
export type PersistableShot = Shot;

export interface UseDisplayedShotsResult {
  /** MultiShotPositionEditor に渡す全スロット (詳細 + 自動補完) */
  displayedShots: DisplayedShot[];
  /** 保存パイプラインに渡す shots (= 詳細記録のみ) */
  persistableShots: PersistableShot[];
  /** 詳細記録数 > 打数 の不整合があるなら警告メッセージ (UI でバナー表示) */
  mismatchWarning: string | null;
}

export interface UseDisplayedShotsArgs {
  /** ShotRecorder の getShotsForHoleLocal 経由で取得した詳細記録 (cache + form 合成済み) */
  existingShots: Shot[];
  /** Stepper の打数値 (null なら par 採用) */
  strokes: number | null;
  /** Stepper のパット数値 (null なら 2 採用) */
  putts: number | null;
  /** ホールの規定打数 */
  par: number;
  /** ホール番号 (合成 shot の hole_number に使用) */
  holeNumber: number;
  /** ラウンド ID (合成 shot の round_id に使用) */
  roundId: string;
  /** ホールの map data (centerline / ref_start/end / areas を内包) */
  mapData: HoleMapData | null;
  /** 使用中グリーン (A / B) */
  activeGreen: 'A' | 'B' | null;
}

/**
 * 自動補完スロットを Shot 形 (id = '', 位置のみ、他は null) に変換
 */
function autoSlotToShot(
  slot: AutoTrajectorySlot,
  shotNumber: number,
  holeNumber: number,
  roundId: string,
): DisplayedShot {
  return {
    id: '',
    round_id: roundId,
    hole_number: holeNumber,
    shot_number: shotNumber,
    club: null,
    result: null,
    miss_type: null,
    direction_lr: null,
    direction_fb: null,
    lie: null,
    slope_fb: null,
    slope_lr: null,
    landing: null,
    shot_type: slot.isPutt ? 'putt' : null,
    remaining_distance: null,
    advice_text: null,
    note: null,
    wind_direction: null,
    wind_strength: null,
    elevation: null,
    latitude: slot.lat,
    longitude: slot.lng,
    gps_accuracy_m: null,
    captured_at: null,
    auto_lie: null,
    remaining_to_green_m: null,
    // 自動スロットは DB 保存しない (id='' のまま)。isAutoGenerated フラグで識別する想定。
    // PR2 でドラッグして DB 保存される際に gps_source='manual_edit' として永続化される
    // ため、表示用の仮値として 'manual_edit' を入れている (DB enum 整合性の影響なし)。
    gps_source: 'manual_edit',
    original_latitude: null,
    original_longitude: null,
    edited_at: null,
    auto_lie_confidence: null,
    position_revision: 0,
    auto_lie_calculated_at: null,
    isAutoGenerated: true,
  };
}

/**
 * メイン hook
 */
export function useDisplayedShots(args: UseDisplayedShotsArgs): UseDisplayedShotsResult {
  return useMemo(() => {
    const persistableShots: PersistableShot[] = args.existingShots;

    // clamp 後の理論合計スロット数 (auto-trajectory と同じ仕様)
    // 注: 詳細な clamp (putts も含む) は computeInitialPositions 内で完結する。
    //     mapData=null の早期 return パスでは initialPositions が計算できないため、
    //     fallback として strokes ベースで判定する (computeInitialPositions の clamp と同等)
    const strokes = Math.max(1, args.strokes ?? args.par);

    // mapData / centerline 取得不可なら自動補完しない (詳細記録のみ表示)
    if (!args.mapData) {
      return {
        displayedShots: args.existingShots.map((s) => ({ ...s, isAutoGenerated: false })),
        persistableShots,
        mismatchWarning:
          args.existingShots.length > strokes
            ? `打数 ${strokes} とショット記録 ${args.existingShots.length} 件が一致しません。`
            : null,
      };
    }

    const centerline = pickCenterline({
      centerlineA: args.mapData.centerlineA,
      centerlineB: args.mapData.centerlineB,
      refStart: args.mapData.refStart,
      refEnd: args.mapData.refEnd,
      activeGreen: args.activeGreen,
    });
    if (!centerline) {
      return {
        displayedShots: args.existingShots.map((s) => ({ ...s, isAutoGenerated: false })),
        persistableShots,
        mismatchWarning:
          args.existingShots.length > strokes
            ? `打数 ${strokes} とショット記録 ${args.existingShots.length} 件が一致しません。`
            : null,
      };
    }

    // greenCenter: hole_areas の green_a/b ポリゴン重心、なければ centerline 最後の点
    const greenAreaType = args.activeGreen === 'B' ? 'green_b' : 'green_a';
    const greenArea: HoleArea | undefined = args.mapData.areas.find((a) => a.area_type === greenAreaType);
    const greenCenter =
      (greenArea ? computeGreenCenter(greenArea.coordinates) : null) ??
      centerline[centerline.length - 1];

    // 自動軌跡の理論位置
    const initialPositions = computeInitialPositions({
      strokes: args.strokes,
      putts: args.putts,
      par: args.par,
      centerline,
      greenCenter,
    });

    // 詳細記録の数だけ自動スロットを置換
    // (詳細記録は shot_number 順にソート済みと仮定、cache の順序に従う)
    const sortedExisting = [...args.existingShots].sort(
      (a, b) => a.shot_number - b.shot_number,
    );
    const displayedShots: DisplayedShot[] = [];
    for (let i = 0; i < initialPositions.length; i++) {
      const existingShot = sortedExisting[i];
      if (existingShot) {
        // 既存詳細記録あり: そのまま使う
        displayedShots.push({ ...existingShot, isAutoGenerated: false });
      } else {
        // 自動補完
        const shotNumber = i + 1;
        displayedShots.push(
          autoSlotToShot(initialPositions[i], shotNumber, args.holeNumber, args.roundId),
        );
      }
    }

    // 不整合: 詳細記録が initialPositions より多い場合は超過分も表示 (データロス防止)
    if (sortedExisting.length > initialPositions.length) {
      for (let i = initialPositions.length; i < sortedExisting.length; i++) {
        displayedShots.push({ ...sortedExisting[i], isAutoGenerated: false });
      }
    }

    // mismatchWarning は initialPositions.length ベースで判定 (single source of truth)
    // computeInitialPositions 内部の clamp 仕様変更に追随する設計
    const mismatchWarning =
      args.existingShots.length > initialPositions.length
        ? `打数 ${strokes} とショット記録 ${args.existingShots.length} 件が一致しません。`
        : null;

    return { displayedShots, persistableShots, mismatchWarning };
  }, [
    args.existingShots,
    args.strokes,
    args.putts,
    args.par,
    args.holeNumber,
    args.roundId,
    args.mapData,
    args.activeGreen,
  ]);
}
