import { describe, it, expect } from 'vitest';
import { renderHook } from '@testing-library/react';
import { useDisplayedShots } from './use-displayed-shots';
import type { Shot } from '@/features/score/types';
import type { HoleMapData, CenterlinePoint } from '@/actions/hole-map';
import type { AerialImageMetadata, HoleArea } from '@/lib/geo';

/**
 * Sprint 7 PR1 (S-7a): use-displayed-shots Hook の単体テスト
 *
 * Gemini High 指摘 (shot_number 不連続時のマージバグ) の reproduction + 修正検証を中心に。
 */

const TEE: CenterlinePoint = { lat: 34.0, lng: 131.5 };
const W1: CenterlinePoint = { lat: 34.001, lng: 131.501 };
const GREEN: CenterlinePoint = { lat: 34.003, lng: 131.503 };

const FAKE_METADATA: AerialImageMetadata = {
  bbox: { lat_min: 33.99, lat_max: 34.01, lng_min: 131.49, lng_max: 131.51 },
  pre_rotate_width: 1024,
  pre_rotate_height: 1024,
  rotated_width: 1024,
  rotated_height: 1024,
  final_width: 1024,
  final_height: 1024,
  bearing_rad: 0,
  zoom: 18,
};

const FAKE_GREEN_AREA: HoleArea = {
  id: 'area-green-a',
  hole_id: 'hole-1',
  area_type: 'green_a',
  coordinates: [
    { lat: GREEN.lat - 0.0002, lng: GREEN.lng - 0.0002 },
    { lat: GREEN.lat - 0.0002, lng: GREEN.lng + 0.0002 },
    { lat: GREEN.lat + 0.0002, lng: GREEN.lng + 0.0002 },
    { lat: GREEN.lat + 0.0002, lng: GREEN.lng - 0.0002 },
  ],
  name: null,
  sort_order: 0,
  created_at: '2026-05-13T00:00:00Z',
  updated_at: '2026-05-13T00:00:00Z',
};

function makeMapData(centerlineA: CenterlinePoint[] | null = [TEE, W1, GREEN]): HoleMapData {
  return {
    aerialImageUrl: 'https://example.com/img.png',
    metadata: FAKE_METADATA,
    areas: [FAKE_GREEN_AREA],
    centerlineA,
    centerlineB: null,
    refStart: TEE,
    refEnd: GREEN,
  };
}

function makeShot(overrides: Partial<Shot>): Shot {
  return {
    id: overrides.id ?? `shot-${overrides.shot_number ?? 1}`,
    round_id: 'round-1',
    hole_number: 1,
    shot_number: overrides.shot_number ?? 1,
    club: null,
    result: null,
    miss_type: null,
    direction_lr: null,
    direction_fb: null,
    lie: null,
    slope_fb: null,
    slope_lr: null,
    landing: null,
    shot_type: null,
    remaining_distance: null,
    advice_text: null,
    note: null,
    wind_direction: null,
    wind_strength: null,
    elevation: null,
    latitude: null,
    longitude: null,
    gps_accuracy_m: null,
    captured_at: null,
    auto_lie: null,
    remaining_to_green_m: null,
    gps_source: null,
    original_latitude: null,
    original_longitude: null,
    edited_at: null,
    auto_lie_confidence: null,
    position_revision: 0,
    auto_lie_calculated_at: null,
    ...overrides,
  };
}

describe('useDisplayedShots', () => {
  describe('shot_number ベースマージ (Gemini High 指摘対応)', () => {
    it('既存ショットが shot_number=[1, 3] で不連続 → スロット 2 は自動補完、shot_number 重複なし', () => {
      const existingShots: Shot[] = [
        makeShot({ id: 'shot-1', shot_number: 1, latitude: 34.0001, longitude: 131.5001 }),
        makeShot({ id: 'shot-3', shot_number: 3, latitude: 34.0003, longitude: 131.5003 }),
      ];
      const { result } = renderHook(() =>
        useDisplayedShots({
          existingShots,
          strokes: 4, // shotCount=2, putts=2 → スロット 4 個
          putts: 2,
          par: 4,
          holeNumber: 1,
          roundId: 'round-1',
          mapData: makeMapData(),
          activeGreen: 'A',
        }),
      );

      expect(result.current.displayedShots).toHaveLength(4);

      const shotNumbers = result.current.displayedShots.map((s) => s.shot_number);
      // 1..4 で重複なし
      expect(shotNumbers).toEqual([1, 2, 3, 4]);

      // shot_number=1 は既存 (id='shot-1')
      expect(result.current.displayedShots[0].id).toBe('shot-1');
      expect(result.current.displayedShots[0].isAutoGenerated).toBe(false);

      // shot_number=2 は自動補完 (id='')
      expect(result.current.displayedShots[1].id).toBe('');
      expect(result.current.displayedShots[1].isAutoGenerated).toBe(true);

      // shot_number=3 は既存 (id='shot-3')
      expect(result.current.displayedShots[2].id).toBe('shot-3');
      expect(result.current.displayedShots[2].isAutoGenerated).toBe(false);

      // shot_number=4 は自動補完 (パット)
      expect(result.current.displayedShots[3].id).toBe('');
      expect(result.current.displayedShots[3].isAutoGenerated).toBe(true);
    });

    it('既存ショットが shot_number=[1, 2, 3] 連続 → 自動スロットは 4 番目のみ', () => {
      const existingShots: Shot[] = [
        makeShot({ id: 'shot-1', shot_number: 1 }),
        makeShot({ id: 'shot-2', shot_number: 2 }),
        makeShot({ id: 'shot-3', shot_number: 3 }),
      ];
      const { result } = renderHook(() =>
        useDisplayedShots({
          existingShots,
          strokes: 4,
          putts: 2,
          par: 4,
          holeNumber: 1,
          roundId: 'round-1',
          mapData: makeMapData(),
          activeGreen: 'A',
        }),
      );

      expect(result.current.displayedShots).toHaveLength(4);
      expect(result.current.displayedShots.map((s) => s.id)).toEqual([
        'shot-1',
        'shot-2',
        'shot-3',
        '', // 自動
      ]);
      expect(result.current.displayedShots.map((s) => s.isAutoGenerated)).toEqual([
        false,
        false,
        false,
        true,
      ]);
    });

    it('既存ショットが shot_number=[1, 5] (打数 4 を超過) → 5 は overflow として末尾追加', () => {
      const existingShots: Shot[] = [
        makeShot({ id: 'shot-1', shot_number: 1 }),
        makeShot({ id: 'shot-5', shot_number: 5 }),
      ];
      const { result } = renderHook(() =>
        useDisplayedShots({
          existingShots,
          strokes: 4, // スロット 4 個
          putts: 2,
          par: 4,
          holeNumber: 1,
          roundId: 'round-1',
          mapData: makeMapData(),
          activeGreen: 'A',
        }),
      );

      expect(result.current.displayedShots).toHaveLength(5); // 4 + overflow 1
      const ids = result.current.displayedShots.map((s) => s.id);
      // 先頭 4 つはスロット 1..4 (1=既存、2/3/4=自動)、最後が overflow shot-5
      expect(ids[0]).toBe('shot-1');
      expect(ids[1]).toBe('');
      expect(ids[2]).toBe('');
      expect(ids[3]).toBe('');
      expect(ids[4]).toBe('shot-5');

      // overflow があるので mismatchWarning が立つ
      expect(result.current.mismatchWarning).not.toBeNull();
      expect(result.current.mismatchWarning).toContain('打数 4');
      expect(result.current.mismatchWarning).toContain('2 件');
    });
  });

  describe('mismatchWarning', () => {
    it('overflow なし → null', () => {
      const { result } = renderHook(() =>
        useDisplayedShots({
          existingShots: [makeShot({ id: 'shot-1', shot_number: 1 })],
          strokes: 4,
          putts: 2,
          par: 4,
          holeNumber: 1,
          roundId: 'round-1',
          mapData: makeMapData(),
          activeGreen: 'A',
        }),
      );
      expect(result.current.mismatchWarning).toBeNull();
    });

    it('mapData=null + 既存ショット数 > strokes → 警告', () => {
      const existingShots: Shot[] = [
        makeShot({ id: 'shot-1', shot_number: 1 }),
        makeShot({ id: 'shot-2', shot_number: 2 }),
        makeShot({ id: 'shot-3', shot_number: 3 }),
        makeShot({ id: 'shot-4', shot_number: 4 }),
        makeShot({ id: 'shot-5', shot_number: 5 }),
      ];
      const { result } = renderHook(() =>
        useDisplayedShots({
          existingShots,
          strokes: 3,
          putts: 2,
          par: 4,
          holeNumber: 1,
          roundId: 'round-1',
          mapData: null,
          activeGreen: 'A',
        }),
      );
      expect(result.current.mismatchWarning).toContain('打数 3');
      expect(result.current.mismatchWarning).toContain('5 件');
    });
  });

  describe('persistableShots', () => {
    it('自動スロットが追加されても persistableShots は existingShots そのまま (型分離)', () => {
      const existingShots: Shot[] = [makeShot({ id: 'shot-1', shot_number: 1 })];
      const { result } = renderHook(() =>
        useDisplayedShots({
          existingShots,
          strokes: 4,
          putts: 2,
          par: 4,
          holeNumber: 1,
          roundId: 'round-1',
          mapData: makeMapData(),
          activeGreen: 'A',
        }),
      );
      expect(result.current.persistableShots).toEqual(existingShots);
      expect(result.current.persistableShots).toHaveLength(1);
      // displayedShots は 4 個 (1 既存 + 3 自動)
      expect(result.current.displayedShots).toHaveLength(4);
    });
  });

  describe('mapData / centerline 不在時のフォールバック', () => {
    it('mapData=null → 自動補完なし、displayedShots = existingShots', () => {
      const existingShots: Shot[] = [
        makeShot({ id: 'shot-1', shot_number: 1 }),
        makeShot({ id: 'shot-2', shot_number: 2 }),
      ];
      const { result } = renderHook(() =>
        useDisplayedShots({
          existingShots,
          strokes: 4,
          putts: 2,
          par: 4,
          holeNumber: 1,
          roundId: 'round-1',
          mapData: null,
          activeGreen: 'A',
        }),
      );
      expect(result.current.displayedShots).toHaveLength(2);
      expect(result.current.displayedShots.every((s) => !s.isAutoGenerated)).toBe(true);
    });

    it('centerline / refStart/End が全部 null → 自動補完なし', () => {
      const mapData: HoleMapData = {
        ...makeMapData(),
        centerlineA: null,
        centerlineB: null,
        refStart: null,
        refEnd: null,
      };
      const { result } = renderHook(() =>
        useDisplayedShots({
          existingShots: [],
          strokes: 4,
          putts: 2,
          par: 4,
          holeNumber: 1,
          roundId: 'round-1',
          mapData,
          activeGreen: 'A',
        }),
      );
      expect(result.current.displayedShots).toHaveLength(0);
    });

    it('centerline=null だが refStart/End あり → 段 2 fallback で自動補完される', () => {
      const mapData: HoleMapData = {
        ...makeMapData(),
        centerlineA: null,
        centerlineB: null,
      };
      const { result } = renderHook(() =>
        useDisplayedShots({
          existingShots: [],
          strokes: 4,
          putts: 2,
          par: 4,
          holeNumber: 1,
          roundId: 'round-1',
          mapData,
          activeGreen: 'A',
        }),
      );
      expect(result.current.displayedShots).toHaveLength(4);
      expect(result.current.displayedShots.every((s) => s.isAutoGenerated)).toBe(true);
    });
  });
});
